Synthetic Data / Backend Added
Biomaterials-for-Medical-Devices-AI/BioFEFI pull request #100
Opened 2024-10-30 13:29 UTC by Karthi-DStech

Hi all, 

I have added backend scripts which is required for creating synthetic data. 

In the following PR, I'll implement the streamlit part. 

Kindly review and do the needful. 

Thanks and regards, 
Karthik

2024-10-30 13:47 UTC, dcl10 requested changes
I would also add a new options class like those in `biofefi.options` since we're migrating to using those, going forward.

2024-11-07 17:55 UTC, Karthi-DStech commented on biofefi/machine_learning/data.py
> +        self._create_synthetic_data = None
Sure. I'll make the changes.

2024-11-07 18:01 UTC, Karthi-DStech commented on biofefi/machine_learning/data.py
> +                raise ValueError(f"Error loading the data through CSV file: {e}")
make sense. I'll implement it.

2024-11-07 18:11 UTC, Karthi-DStech commented
> I would also add a new options class like those in `biofefi.options` since we're migrating to using those, going forward.

I have no problem implementing the options you mentioned. However, I was concerned about changing the options dynamically. 

As we can see, all the options mentioned in `biofefi.options` are static. What would be the case if we want to use the options as per custom requirements (eg: if the user needs to specify the number of features and training samples as per their requirements)? 

can we have a short discussion about this so I can implement it? 

Thanks and regards,
Karthik

2024-11-13 14:17 UTC, dcl10 commented
Hi @Karthi-DStech, so sorry for taking so long to get back to you. There's been quite a few changes to the app in the time you've been off. Let's leave this PR open until you get back and then we'll discuss how to move this forward.

2024-11-21 09:13 UTC, dcl10 commented
Hi @Karthi-DStech, I'm really sorry about this but I'm going to close this PR without merging. We recently did a large refactor of the way we handle options throughout the app. Also I have some other concerns around the design of making synthetic data. We can discuss it when you get back.

2024-11-21 09:13 UTC, closed without merging