Added checkbutton for save plots option and text input for dependent …
Biomaterials-for-Medical-Devices-AI/BioFEFI pull request #118
Opened 2024-11-11 11:47 UTC by EdAguilarB

…variable name

2024-11-11 11:57 UTC, dcl10 commented
@EdAguilarB Is this related to #116 ?

2024-11-11 11:58 UTC, EdAguilarB commented
> @EdAguilarB Is this related to #116 ?

Yes!

2024-11-11 12:02 UTC, dcl10 requested changes

2024-11-11 12:02 UTC, dcl10 commented on biofefi/components/forms.py
> +    save_plots = st.checkbox(
If you look at the ML page now that it's merged, do you think you could put all the options to save outputs at the bottom like on the ML page. Also could you use `st.toggle` for those options, like on the ML page pls?

2024-11-12 09:34 UTC, dcl10 commented on biofefi/services/ml_models.py
> +def load_model_explain(path: Path, model_names: list) -> dict[str, list]:
```suggestion
def load_models_to_explain(path: Path, model_names: list) -> dict[str, list]:
```
⛏️

2024-11-12 09:55 UTC, dcl10 approved these changes

2024-11-12 12:07 UTC, merged