Check existing ml
Biomaterials-for-Medical-Devices-AI/BioFEFI pull request #129
Opened 2024-11-19 13:21 UTC by EdAguilarB

## Description
Added check buttons to, in case that there is already a model saved in the experiment, ask the user if run the experiment again and overwrite previous results. 
Also corrected a small error in the FI page that caused the page to crash.

## Linked issues
- #127 

## (Optional) Screenshots
<img width="741" alt="image" src="https://github.com/user-attachments/assets/34602ce1-43e6-40b8-b97d-c0095a99e114">
<img width="741" alt="image" src="https://github.com/user-attachments/assets/8c191f29-90d5-43e3-8287-a91ab020d9f0">
<img width="741" alt="image" src="https://github.com/user-attachments/assets/947b95a7-c2f0-419e-9af2-8493ed679065">
<img width="741" alt="image" src="https://github.com/user-attachments/assets/dca9c811-f5f5-4dc5-8a6c-53eea710dc77">
<img width="754" alt="image" src="https://github.com/user-attachments/assets/57941f48-da1c-457c-a51c-a4ae13815c99">
<img width="754" alt="image" src="https://github.com/user-attachments/assets/8989cffa-c9ea-45ce-8901-428afe97a91b">
<img width="754" alt="image" src="https://github.com/user-attachments/assets/bf8c8f69-16d8-40f6-b209-67591576d56f">
<img width="754" alt="image" src="https://github.com/user-attachments/assets/c0fb0093-dbaf-4f75-99dc-8173c2aa5000">

2024-11-19 14:59 UTC, dcl10 requested changes

2024-11-19 14:59 UTC, dcl10 commented on biofefi/components/forms.py
> +    ):
```suggestion
    if (
        st.session_state.get(ConfigStateKeys.ProblemType, ProblemTypes.Auto).lower()
        == ProblemTypes.Regression
    ):
```

2024-11-19 14:59 UTC, dcl10 commented on biofefi/components/forms.py
> +        == ProblemTypes.Classification
```suggestion
        st.session_state.get(ConfigStateKeys.ProblemType, ProblemTypes.Auto).lower()
        == ProblemTypes.Classification
```

2024-11-19 14:59 UTC, dcl10 commented on biofefi/components/forms.py
I think we should keep it simple for now and just ask if the user wants to totally restart if any models exist at all. The way you've done it now would require a new `if` block for every single model we implement.

2024-11-19 16:11 UTC, EdAguilarB commented on biofefi/components/forms.py
So, just one check and if the user wants to re run, it will re run everything?

2024-11-19 16:12 UTC, dcl10 commented on biofefi/components/forms.py
Yes

2024-11-20 06:51 UTC, EdAguilarB commented
This is how it is displayed:

<img width="725" alt="image" src="https://github.com/user-attachments/assets/1f97bbd3-9d56-4928-93b0-0e35eeca5195">

If user chooses to not rerun and clicks Run Training:

<img width="725" alt="image" src="https://github.com/user-attachments/assets/e16324d6-92ae-4488-a31e-c2c800a0ec28">

2024-11-20 09:30 UTC, dcl10 approved these changes

2024-11-20 12:01 UTC, dcl10 requested changes

2024-11-20 12:38 UTC, dcl10 requested changes

2024-11-20 15:14 UTC, dcl10 approved these changes

2024-11-20 15:16 UTC, merged